[workspace]
members = [
  "crates/dovecote",
  "crates/dovecote-sqlx-postgres",
  "crates/dovecote-sqlx-mysql",
  "crates/dovecote-sqlx-sqlite",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.94"
version = "0.2.1"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/plethu/dovecote"
homepage = "https://github.com/plethu/dovecote"
keywords = ["transactional-outbox", "cloudevents", "sqlx"]
categories = ["database", "asynchronous"]

[workspace.dependencies]
base64 = "0.22.1"
cloudevents = { package = "cloudevents-sdk", version = "0.9.0" }
dovecote = { path = "crates/dovecote", version = "0.2.1" }
getrandom = "0.4.3"
jsonschema = { version = "0.52.0", default-features = false }
mime = "0.3.17"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["preserve_order"] }
sqlx = { version = "0.9.0", default-features = false }
thiserror = "2.0.12"
time = { version = "0.3.41", features = ["formatting", "macros", "parsing"] }
fluent-uri = "0.4.1"
