[package]
name = "dovecote-sqlx-postgres"
description = "PostgreSQL SQLx adapter for Dovecote"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
dovecote.workspace = true
getrandom.workspace = true
sqlx = { workspace = true, features = ["postgres", "time", "macros"] }
thiserror.workspace = true
time.workspace = true

[features]
default = ["runtime-tokio"]
runtime-tokio = ["sqlx/runtime-tokio"]

[dev-dependencies]
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "time"] }
