[package]
name = "carrier-sqlx-postgres"
description = "PostgreSQL SQLx adapter for Carrier"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
carrier.workspace = true
sqlx = { workspace = true, features = ["postgres", "time"] }

[features]
default = ["runtime-tokio"]
runtime-tokio = ["sqlx/runtime-tokio"]
