[package]
name = "carrier-sqlx-mysql"
description = "MySQL and MariaDB SQLx adapter for Carrier"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
carrier.workspace = true
sqlx = { workspace = true, features = ["mysql", "time"] }

[features]
default = ["runtime-tokio"]
runtime-tokio = ["sqlx/runtime-tokio"]
